### ISSUE TITLE
能否提供一下glxss pro的sdk文件

### ISSUE THREAD

**Issue by HowToLoveChina** [goldsail/Custom_SDK_Configuration#1]
有设备找不到sdk的下载，希望能获得您的帮助

**Comment by goldsail** [comment]
您好！本仓库的教程是针对 Android Studio 导入第三方SDK的需求，给出一个参考的步骤，也是本人在使用这个SDK过程中的笔记。至于这个SDK本身，是北京亮亮视野科技有限公司的私有产品，本人无权公开；请您与该公司联系，谢谢！

Thanks for your question. This repo is a documentation about how to import third-party SDKs into Android Studio. I took down this note when using the GLXSS Pro SDK in 2017. The GLXSS Pro SDK, however, is the proprietary product of LLVision Inc., Beijing, and therefore I cannot provide the link without permission. Please contact the company for more information. Thank you!
